package javaapplication24;

import javax.swing.table.DefaultTableModel;
import static javaapplication24.dbKoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class jPasien extends javax.swing.JFrame {

    DefaultTableModel DM = new DefaultTableModel();
    /**
     * Creates new form fMahasiswa
     */
    public jPasien() throws SQLException {
        initComponents();
        TM.setModel(DM);
        DM.addColumn("ID");
        DM.addColumn("Nama Pasien");
        
        cleartexField();
        ListDataTable();
        tombol(false);
        cBARU.setEnabled(true);
        
    }
  private void tombol(boolean opsi)  {
  cBARU.setEnabled(opsi);
  cUBAH.setEnabled(opsi);
  cHAPUS.setEnabled(opsi);
  }
  private void cleartexField(){
        txID.setText("");
        txNAMA.setText("");
        txUMUR.setText("");
        txJENIS_KELAMIN.setText("");
        txALAMAT.setText("");
        txTANGGAL_DAFTAR.setText("");
    }
    private void ListDataTable() throws SQLException{
        Connection cnn = koneksi();
        
        DM.getDataVector().removeAllElements();
        DM.fireTableDataChanged();
        
        if(!cnn.isClosed()){
            PreparedStatement PS= cnn.prepareStatement("SELECT * FROM mhs;");
            ResultSet RS = PS.executeQuery();
            
            while(RS.next()){
                Object[] dta = new Object[3];
                dta[0] = RS.getString("ID");
                dta[1] = RS.getString("NAMA");
                dta[2] = RS.getString("UMUR");
                dta[3] = RS.getString("JENIS_KELAMIN");
                dta[4] = RS.getString("ALAMAT");
                dta[5] = RS.getString("TANGGAL_DAFTAR");
                
                
                DM.addRow(dta);
              
            }
            cnn.close();
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private static class cBARU {

        private static void setEnabled(boolean opsi) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        public cBARU() {
        }
    }

    private static class TM {

        private static void setModel(DefaultTableModel DM) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        public TM() {
        }
    }

    private static class cUBAH {

        private static void setEnabled(boolean opsi) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        public cUBAH() {
        }
    }

    private static class cHAPUS {

        private static void setEnabled(boolean opsi) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        public cHAPUS() {
        }
    }


    private static class txID {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txID() {
        }
    }

    private static class txNAMA {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txNAMA() {
        }
    }

    private static class txUMUR {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        public txUMUR() {
        }
    }

    private static class txJENIS_KELAMIN {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }
        public txJENIS_KELAMIN() {
        }
    }

    private static class txTANGGAL_LAHIR {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        public txTANGGAL_LAHIR() {
        }
    }

    private static class txALAMAT {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet.");  
        }

        public txALAMAT() {
        }
    }

    private static class txTANGGAL_DAFTAR {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        public txTANGGAL_DAFTAR() {
        }
    }
     
        
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TM = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txNIM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txPASIEN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UMUR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txJENIS_KELAMIN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txTANGGAL_DAFTAR = new javax.swing.JTextField();
        cBARU = new javax.swing.JTextField();
        cUBAH = new javax.swing.JTextField();
        cHAPUS = new javax.swing.JTextField();
        cTUTUP = new javax.swing.JTextField();

        jLabel5.setText("ALAMAT");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel1.setText("Data Pasien");

        TM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(TM);

        jLabel2.setText("Edit View Data");

        jLabel3.setText("ID");

        txNIM.setText("jTextField4");
        txNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIMActionPerformed(evt);
            }
        });

        jLabel4.setText("NAMA PASIEN");

        txPASIEN.setText("jTextField1");
        txPASIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPASIENActionPerformed(evt);
            }
        });

        jLabel8.setText("UMUR");

        UMUR.setText("jTextField2");

        jLabel9.setText("JENIS_KELAMIN");

        txJENIS_KELAMIN.setText("jTextField3");
        txJENIS_KELAMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJENIS_KELAMINActionPerformed(evt);
            }
        });

        jLabel10.setText("ALAMAT");

        jTextField.setText("jTextField5");
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("TANGGAL_DAFTAR");

        txTANGGAL_DAFTAR.setText("jTextField6");

        cBARU.setText("BARU");
        cBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBARUActionPerformed(evt);
            }
        });

        cUBAH.setText("UBAH");

        cHAPUS.setText("HAPUS");

        cTUTUP.setText("TUTUP");
        cTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTUTUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cBARU, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(134, 134, 134)
                                    .addComponent(cUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(114, 114, 114)
                                    .addComponent(cHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                    .addComponent(cTUTUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(txNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addComponent(txJENIS_KELAMIN))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txPASIEN, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel10))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8)
                                        .addComponent(UMUR, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addComponent(txTANGGAL_DAFTAR)))))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPASIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UMUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txJENIS_KELAMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txTANGGAL_DAFTAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBARU, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTUTUP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIMActionPerformed

    private void txPASIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPASIENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPASIENActionPerformed

    private void txJENIS_KELAMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJENIS_KELAMINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJENIS_KELAMINActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void cBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBARUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBARUActionPerformed

    private void cTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTUTUPActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_cTUTUPActionPerformed

   

        /* Create and display the form */
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TM;
    private javax.swing.JTextField UMUR;
    private javax.swing.JTextField cBARU;
    private javax.swing.JTextField cHAPUS;
    private javax.swing.JTextField cTUTUP;
    private javax.swing.JTextField cUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTextField txJENIS_KELAMIN;
    private javax.swing.JTextField txNIM;
    private javax.swing.JTextField txPASIEN;
    private javax.swing.JTextField txTANGGAL_DAFTAR;
    // End of variables declaration//GEN-END:variables


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new jPasien().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(jPasien.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
}